[build]
builder = "NIXPACKS"
buildCommand = "cd backend-src && npm install && npm run build"

[deploy]
startCommand = "cd backend-src && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"